pt_SFX:	dw SFX_01, SFX_02, SFX_03, SFX_04
		dw SFX_05, SFX_06, SFX_07, SFX_08
		dw SFX_09, SFX_0A, SFX_0B, SFX_0C
		dw SFX_0D, SFX_0E, SFX_0F, SFX_10
		dw SFX_11, SFX_12, SFX_13, SFX_14
		dw SFX_15, SFX_16, SFX_17, SFX_18
		dw SFX_19, SFX_1A, SFX_1B, SFX_1C
		dw SFX_1D, SFX_1E, SFX_1F, SFX_20
		dw SFX_21, SFX_22, SFX_23, SFX_24
		dw SFX_25, SFX_26, SFX_27, SFX_28
		dw SFX_29, SFX_2A, SFX_2B, SFX_2C
		dw SFX_2D, SFX_2E, SFX_2F, SFX_30
		dw SFX_31, SFX_32, SFX_33, SFX_34
		dw SFX_35, SFX_36, SFX_37, SFX_38
		dw SFX_39, SFX_3A

SFX_01:        include "sfx/sfx01_header.asm"
               include "sfx/sfx01_data.asm"
SFX_02:        include "sfx/sfx02_header.asm"
               include "sfx/sfx02_data.asm"
SFX_03:        include "sfx/sfx03_header.asm"
               include "sfx/sfx03_data.asm"
SFX_04:        include "sfx/sfx04_header.asm"
               include "sfx/sfx04_data.asm"
SFX_05:        include "sfx/sfx05_header.asm"
SFX_06:        include "sfx/sfx06_header.asm"
SFX_07:        include "sfx/sfx07_header.asm"
SFX_08:        include "sfx/sfx08_header.asm"
SFX_09:        include "sfx/sfx09_header.asm"
SFX_0A:        include "sfx/sfx0A_header.asm"
SFX_0B:        include "sfx/sfx0B_header.asm"
SFX_0C:        include "sfx/sfx0C_header.asm"
               include "sfx/sfx05_data.asm"
               include "sfx/sfx06_data.asm"
               include "sfx/sfx07_data.asm"
               include "sfx/sfx08_data.asm"
               include "sfx/sfx09_data.asm"
               include "sfx/sfx0A_data.asm"
               include "sfx/sfx0B_data.asm"
               include "sfx/sfx0C_data.asm"
SFX_0D:        include "sfx/sfx0D_header.asm"
               include "sfx/sfx0D_data.asm"
SFX_0E:        include "sfx/sfx0E_header.asm"
			   include "sfx/sfx0E_data.asm"
SFX_0F:        include "sfx/sfx0F_header.asm"
			   include "sfx/sfx0F_data.asm"
SFX_10:        include "sfx/sfx10_header.asm"
			   include "sfx/sfx10_data.asm"
SFX_UNUSED1:   include "sfx/sfx_unused1_header.asm"
			   include "sfx/sfx_unused1_data.asm"
SFX_11:        include "sfx/sfx11_header.asm"
			   include "sfx/sfx11_data.asm"
SFX_12:        include "sfx/sfx12_header.asm"
			   include "sfx/sfx12_data.asm"
SFX_13:        include "sfx/sfx13_header.asm"
			   include "sfx/sfx13_data.asm"
SFX_14:        include "sfx/sfx14_header.asm"
			   include "sfx/sfx14_data.asm"
SFX_15:        include "sfx/sfx15_header.asm"
			   include "sfx/sfx15_data.asm"
SFX_16:        include "sfx/sfx16_header.asm"
			   include "sfx/sfx16_data.asm"
SFX_1F:        include "sfx/sfx1F_header.asm"
			   include "sfx/sfx1F_data.asm"
SFX_17:        include "sfx/sfx17_header.asm"
			   include "sfx/sfx17_data.asm"
SFX_18:        include "sfx/sfx18_header.asm"
			   include "sfx/sfx18_data.asm"
SFX_1A:        include "sfx/sfx1A_header.asm"
			   include "sfx/sfx1A_data.asm"
SFX_19:        include "sfx/sfx19_header.asm"
			   include "sfx/sfx19_data.asm"
SFX_1B:        include "sfx/sfx1B_header.asm"
			   include "sfx/sfx1B_data.asm"
SFX_1D:        include "sfx/sfx1D_header.asm"
			   include "sfx/sfx1D_data.asm"
SFX_1C:        include "sfx/sfx1C_header.asm"
			   include "sfx/sfx1C_data.asm"
SFX_1E:        include "sfx/sfx1E_header.asm"
			   include "sfx/sfx1E_data.asm"
SFX_20:        include "sfx/sfx20_header.asm"
			   include "sfx/sfx20_data.asm"
SFX_28:        include "sfx/sfx28_header.asm"
			   include "sfx/sfx28_data.asm"
SFX_29:        include "sfx/sfx29_header.asm"
			   include "sfx/sfx29_data.asm"
SFX_2A:        include "sfx/sfx2A_header.asm"
			   include "sfx/sfx2A_data.asm"
SFX_2B:        include "sfx/sfx2B_header.asm"
			   include "sfx/sfx2B_data.asm"
SFX_2C:        include "sfx/sfx2C_header.asm"
			   include "sfx/sfx2C_data.asm"
SFX_2D:        include "sfx/sfx2D_header.asm"
			   include "sfx/sfx2D_data.asm"
SFX_2E:        include "sfx/sfx2E_header.asm"
			   include "sfx/sfx2E_data.asm"
SFX_33:        include "sfx/sfx33_header.asm"
			   include "sfx/sfx33_data.asm"
SFX_34:        include "sfx/sfx34_header.asm"
			   include "sfx/sfx34_data.asm"
SFX_36:        include "sfx/sfx36_header.asm"
			   include "sfx/sfx36_data.asm"
SFX_35:        include "sfx/sfx35_header.asm"
			   include "sfx/sfx35_data.asm"
SFX_39:        include "sfx/sfx39_header.asm"
			   include "sfx/sfx39_data.asm"
SFX_38:        include "sfx/sfx38_header.asm"
			   include "sfx/sfx38_data.asm"
SFX_37:        include "sfx/sfx37_header.asm"
			   include "sfx/sfx37_data.asm"
SFX_3A:        include "sfx/sfx3A_header.asm"
			   include "sfx/sfx3A_data.asm"
SFX_21:        include "sfx/sfx21_header.asm"
			   include "sfx/sfx21_data.asm"
SFX_22:        include "sfx/sfx22_header.asm"
			   include "sfx/sfx22_data.asm"
SFX_23:        include "sfx/sfx23_header.asm"
			   include "sfx/sfx23_data.asm"
SFX_24:        include "sfx/sfx24_header.asm"
			   include "sfx/sfx24_data.asm"
SFX_25:        include "sfx/sfx25_header.asm"
			   include "sfx/sfx25_data.asm"
SFX_26:        include "sfx/sfx26_header.asm"
			   include "sfx/sfx26_data.asm"
SFX_27:        include "sfx/sfx27_header.asm"
			   include "sfx/sfx27_data.asm"
SFX_2F:        include "sfx/sfx2F_header.asm"
			   include "sfx/sfx2F_data.asm"
SFX_30:        include "sfx/sfx30_header.asm"
			   include "sfx/sfx30_data.asm"
SFX_31:        include "sfx/sfx31_header.asm"
			   include "sfx/sfx31_data.asm"
SFX_32:        include "sfx/sfx32_header.asm"
			   include "sfx/sfx32_data.asm"
			   include "sfx/sfx_unused2_data.asm"
SFX_UNUSED2:   include "sfx/sfx_unused2_header.asm"
SFX_DUMMY:	   include "sfx/sfx_dummy.asm"
SFX_NOOP:	   include "sfx/sfx_noop.asm"
