USELESS_BYTE:	db 0			; DATA XREF: Main+5Dw
					; YM1_SetStereo:loc_FBAr ...
CURRENT_PSG_CHANNEL:db 0		; DATA XREF: PSG_ParseToneData-6C5r
					; PSG_ParseToneData+17w ...
CURRENT_CHANNEL:db 0			; DATA XREF: Update_YM_InstrumentsLevelso
					; StopMusic+1o	...
CURRENTLY_FADING_OUT:db	0		; DATA XREF: Main+7Cw StopMusic+91w ...
		db    0
CALL_YM2_INSTEAD_OF_YM1:db 0		; DATA XREF: Main-15Aw	Main-140w ...
CURRENTLY_MANAGING_SFX_TYPE_2:db 0	; DATA XREF: Main-15Dw
					; Update_YM_InstrumentsLevels+55w ...
FADE_OUT_LENGTH:db 1			; DATA XREF: UpdateSound+40r
					; FadeOut+2w ...
FADE_OUT_TIMER:	db 63h			; DATA XREF: Main+84w
					; StopMusic:loc_3EEw ...
FADE_OUT_COUNTER:db 0			; DATA XREF: Main+7Fw StopMusic+94w ...
MUSIC_DOESNT_USE_SAMPLES:dw 0		; DATA XREF: Main+68w UpdateSound+24r	...
BANK_TO_LOAD:	db 0			; DATA XREF: LoadBank+5o
					; LoadDacSound+1Dw
MUSIC_BANK_TO_LOAD:db 0			; DATA XREF: LoadMusicBank+8r Main+28w ...
SFX_USELESS_BYTE_2:db 0FFh		; DATA XREF: init+9w Main+135r ...
		db    0
TEMP_FREQUENCY:	dw 0			; DATA XREF: ROM:000006A1w
					; ROM:000006BDr ...
TEMP_REGISTER:	db 0			; DATA XREF: YM1_LoadInstrument+50w
					; YM1_LoadInstrument+66r ...
FADE_IN_TIMER:	db 0			; DATA XREF: Main+5Aw UpdateSound+3o