USELESS_BYTE:					db 0
CURRENT_PSG_CHANNEL:			db 0
CURRENT_CHANNEL:				db 0
CURRENTLY_FADING_OUT:			db 0, 0
CALL_YM2_INSTEAD_OF_YM1:		db 0
CURRENTLY_MANAGING_SFX_TYPE_2:	db 0
FADE_OUT_LENGTH:				db 1
FADE_OUT_TIMER:					db 63h
FADE_OUT_COUNTER:				db 0
MUSIC_DOESNT_USE_SAMPLES:		dw 0
BANK_TO_LOAD:					db 0
MUSIC_BANK_TO_LOAD:				db 0
SFX_USELESS_BYTE_2:				db 0FFh, 0
TEMP_FREQUENCY:					dw 0
TEMP_REGISTER:					db 0
FADE_IN_TIMER:					db 0
