;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; LANDSTALKER FR ROM Disassembly ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; BUILDOPTS = /p /o ae-,e+,w+,c+,op+,os+,ow+,oz+,l_ /e REGION=3;NTSC=0;EXPANDED=0;REGION_CHECK=1;FIX_COLL_1=1;FIX_COLL_2=1;FIX_ARMLET_SKIP=1;FIX_WHISTLE_CHECK=1;FIX_SPRITE_HIDE=1;ENABLE_GOLD_COUNT=1;FIX_GOLA_BUG=1;FIX_GOLD_CAP=1;FIX_END_CREDS=1;REFRESH_GOLD_CTR=0;FIX_TS_GLITCH=1
;; REGION = FR
;;
;; To build, run:
;; .\build\asm68k.exe /p /o ae-,e+,w+,c+,op+,os+,ow+,oz+,l_ /e REGION=3;NTSC=0;EXPANDED=0;REGION_CHECK=1;FIX_COLL_1=1;FIX_COLL_2=1;FIX_ARMLET_SKIP=1;FIX_WHISTLE_CHECK=1;FIX_SPRITE_HIDE=1;ENABLE_GOLD_COUNT=1;FIX_GOLA_BUG=1;FIX_GOLD_CAP=1;FIX_END_CREDS=1;REFRESH_GOLD_CTR=0;FIX_TS_GLITCH=1 landstalker_fr.asm,landstalker_fr.bin

Defines:                    include "code/include/landstalker.inc"
                            include "code/include/landstalker_fr.inc"
                            include "code/include/sram.inc"
                            include "code/include/io.inc"
                            include "code/include/vdp.inc"
                            include "code/include/ram.inc"
                            include "code/include/macros.inc"


                            org     $000000
                            include "code/system/vector_table.asm"
                            include "code/system/header_fr.asm"
                            include "code/system/system_jmps.asm"
                            include "code/system/startup.asm"
                            include "code/system/vdpregs.asm"
                            include "code/system/palette.asm"
                            include "code/system/vdpcopy.asm"
                            include "code/system/systemutil.asm"
                            include "code/system/interrupts.asm"
                            include "code/system/savegame.asm"
                            include "code/gamelogic/gameloop.asm"
                            include "code/gamelogic/playermovement.asm"
                            include "code/maps/lavapalette.asm"
LavaPaletteRotation:        incbin  "assets_packed/graphics/miscpalettes/lavapalette.pal"
                            include "code/maps/mapload.asm"
LabrynthLitPal:             incbin  "assets_packed/graphics/miscpalettes/labrynthlit.pal"
                            include "code/gamelogic/debugcheats.asm"
                            include "code/gamelogic/collision.asm"
                            include "code/gamelogic/gravity.asm"
                            include "code/misc/fridayanimation.asm"
FridayAnimationData:        include "code/misc/fridayanimationdata.asm"
                            include "code/gamelogic/playerjump.asm"
                            include "code/gamelogic/spriterender.asm"
                            include "code/maps/mapflagchanges.asm"
RoomGfxSwapFlags:           incbin  "assets_packed/roomdata/flagactions/roomgfxswapflags.bin"
LockedDoorGfxSwapFlags:     incbin  "assets_packed/roomdata/flagactions/lockeddoorgfxswapflags.bin"
TreeWarpGfxSwapFlags:       incbin  "assets_packed/roomdata/flagactions/treewarpgfxswapflags.bin"
TileSwaps:                  incbin  "assets_packed/roomdata/flagactions/tileswaps.bin"
                            include "code/gamelogic/floortypes.asm"
                            include "code/gamelogic/playeractions.asm"
                            include "code/gamelogic/playeranim.asm"
                            include "code/inventory/inventorymenu.asm"
InvItemPal:                 incbin  "assets_packed/graphics/static/inventory/invitempal.pal"
                            include "code/misc/equipmentpaletteswap.asm"
SwordPalSwaps:              incbin  "assets_packed/graphics/miscpalettes/swordpalswaps.pal"
ArmourPalSwaps:             incbin  "assets_packed/graphics/miscpalettes/armourpalswaps.pal"
                            include "code/inventory/tilemapdma.asm"
SwordGfxData:               include "code/graphics/staticimages/swordfx.asm"
                            Align   $2
                            include "code/items/itemdispatch.asm"
ItemPreUseTable:            include "code/pointertables/items/items_preusejmptable.asm"
ItemPostUseTable:           include "code/pointertables/items/items_postusejmptable.asm"
ItemFuncs1:                 include "code/items/itemuse1.asm"
LightableRooms:             incbin  "assets_packed/roomdata/flagactions/lanternflags.bin"
ItemFuncs2:                 include "code/items/itemuse2.asm"
                            include "code/items/itempostuse.asm"
                            include "code/gamelogic/screeninit.asm"
DefaultPlayerPal:           incbin  "assets_packed/graphics/miscpalettes/defaultplayer.pal"
StatusBarPal:               incbin  "assets_packed/graphics/static/hud/hud.pal"
                            include "code/gamelogic/roominit.asm"
StatusBarTilemap:           incbin  "assets_packed/graphics/static/hud/hudtilemap.map"
StatusBarGfx:               incbin  "assets_packed/graphics/static/hud/hud.lz77"
                            Align   $2
                            include "code/maps/doors.asm"
DoorLookup:                 incbin  "assets_packed/roomdata/misc/doorlookup.bin"
DoorTable:                  incbin  "assets_packed/roomdata/misc/doortable.bin"
                            Align   $2
                            include "code/gamelogic/shops/shopentry.asm"
Shops:                      incbin  "assets_packed/roomdata/misc/shops.bin"
                            include "code/gamelogic/shops/speakerlookup.asm"
                            include "code/gamelogic/shops/lifestockflags.asm"
LifestockSoldFlags:         incbin  "assets_packed/roomdata/flagactions/lifestocksoldflags.bin"
                            include "code/maps/animtilesets.asm"
AnimatedTilesetTable:       include "code/maps/animtilesettbl.asm"
                            include "code/maps/roomwarps.asm"
RoomFallDestination:        incbin  "assets_packed/roomdata/warps/roomfalldests.bin"
RoomClimbDestination:       incbin  "assets_packed/roomdata/warps/roomclimbdests.bin"
RoomTransitionLookup:       incbin  "assets_packed/roomdata/flagactions/roomtransitions.bin"
                            include "code/blocks/loadblockstrips.asm"
                            include "code/blocks/isometricblockcopydata.asm"
                            include "code/blocks/blockptrcalc.asm"
                            include "code/text/introstring_routines.asm"
IntroStrings:               include "code/text/introstrings.asm"
RoomVisitedFlagLookup:      incbin  "assets_packed/roomdata/flagactions/roomvisitflags.bin"
                            include "code/maps/mapdecompress.asm"
                            include "code/blocks/blockdecompress.asm"
                            include "code/inventory/itemmenu.asm"
InventoryItems:             incbin  "assets_packed/misc/inventory/inventoryitems.bin"
                            Align   $2
                            include "code/inventory/itemdraw.asm"
                            include "code/inventory/itemmenuassets.asm"
InventoryGraphics:          include "code/inventory/graphics_fr.asm"
                            Align   $2
                            include "code/graphics/visualeffects.asm"
                            include "code/graphics/warppadfx.asm"
                            include "code/graphics/treewarpfx.asm"
                            include "code/graphics/screenflash.asm"
                            include "code/graphics/nolewarpfx.asm"
KazaltWarpPalette:          incbin  "assets_packed/graphics/miscpalettes/kazaltwarp.pal"
                            include "code/graphics/nolewarpupdate.asm"
                            include "code/inventory/equipmenu.asm"
EquipInventoryLayout:       incbin  "assets_packed/misc/inventory/inventoryequip.bin"
                            Align   $2
                            include "code/inventory/equipmenudraw.asm"
GameLoadScreen:             include "code/title/gameloadscreen.asm"
                            PadTo   $010300
                            include "code/sprites/spritefuncsjumptable.asm"
                            include "code/sprites/spriteanimation.asm"
SpriteAnimFlags:            incbin  "assets_packed/spritedata/spriteanimflags.bin"
                            include "code/gamelogic/playbackinput.asm"
InputPlayback:              incbin  "assets_packed/misc/playbackinputtable.bin"
                            include "code/sprites/playerspecialanim.asm"
BehaviourTriggerJumpTable:  include "code/scripthandling/triggeractionjumptable.asm"
BehaviourTriggerFuncs:      include "code/scripthandling/triggeractions.asm"
CutsceneJumpTable:          include "code/scripthandling/dialogueactionjumptable.asm"
CutsceneFuncs:              include "code/scripthandling/dialogueactions.asm"
                            include "code/scripthandling/dialogueactionshelpers.asm"
                            include "code/gamelogic/combat.asm"
                            include "code/graphics/hud.asm"
                            include "code/graphics/statusanim.asm"
StatusAnimPtrs:             include "code/pointertables/graphics/statusanimptrs.asm"
StatusAnimData:             include "code/graphics/staticimages/statusfx.asm"
                            Align   $2
                            include "code/gamelogic/playerstats.asm"
                            include "code/sprites/spritebehaviourjumptable.asm"
                            include "code/sprites/spritebehaviours.asm"
                            dcb.b   $200, $FF
                            include "code/maps/loadroomsprites.asm"
CustomRoomActions1:         include "code/maps/customroomactions1.asm"
BigTreeLocations:           incbin  "assets_packed/roomdata/misc/bigtreelocs.bin"
CustomRoomActions2:         include "code/maps/customroomactions2.asm"
                            include "code/maps/roomspriteflags.asm"
SpriteVisibilityFlags:      incbin  "assets_packed/roomdata/flagactions/spritevisibility.bin"
OneTimeEventFlags:          incbin  "assets_packed/roomdata/flagactions/onetime.bin"
RoomClearFlags:             incbin  "assets_packed/roomdata/flagactions/roomcleared.bin"
LockedDoorSpriteFlags:      incbin  "assets_packed/roomdata/flagactions/lockeddoorsprites.bin"
PermanentSwitchFlags:       incbin  "assets_packed/roomdata/flagactions/permanentswitches.bin"
SacredTreeFlags:            incbin  "assets_packed/roomdata/flagactions/sacredtrees.bin"
SpriteGfxIdxLookup:         incbin  "assets_packed/spritedata/spritegfx.bin"
SpriteDimensionsLookup:     incbin  "assets_packed/spritedata/spritedimensions.bin"
                            Align   $2
RoomSpriteTableOffset:      incbin  "assets_packed/spritedata/roomtableoffsets.bin"
EnemyStats:                 incbin  "assets_packed/spritedata/enemystats.bin"
RoomSpriteTable:            incbin  "assets_packed/spritedata/roomspritetable.bin"
                            PadTo   $22E80
StringPtrs:                 include "code/pointertables/strings/stringbankptr.asm"
                            include "code/text/stringfuncsjumptable.asm"
                            include "code/text/stringprint.asm"
DownArrowGfx:               incbin  "assets_packed/graphics/static/textbox/downarrow.bin"
                            include "code/text/textbox.asm"
                            include "code/text/glyphrender.asm"
TextBoxTilemap:             incbin  "assets_packed/graphics/static/textbox/threelinetextbox.map"
InventoryTextBoxTilemap:    incbin  "assets_packed/graphics/static/textbox/twolinetextbox.map"
HuffTableOffsets:           incbin  "assets_packed/strings/main/fr/huffmancharoffsets.bin"
HuffTables:                 incbin  "assets_packed/strings/main/fr/huffmantables.bin"
                            Align   $2
                            include "code/text/huffmandecode.asm"
                            include "code/text/textprompts.asm"
RightArrowGfx:              incbin  "assets_packed/graphics/static/textbox/rightarrow.bin"
                            include "code/scripthandling/shops/shopactions.asm"
ShopSpecialItemsScript:     include "code/script/fr/shops/shoptable_specialitems.asm"
                            include "code/scripthandling/shops/shoppricing.asm"
ShopScript:	                include "code/script/fr/shops/shoptable.asm"
                            include "code/scripthandling/scriptfuncs_shopdialogue.asm"
ShopSpecialItemsFuncs:      include "code/script/fr/shops/script_shopspecialitems.asm"
                            include "code/scripthandling/scriptfuncs_speaker.asm"
ScriptProgressFlags:        include "code/script/en/scriptflagcheck.asm"
                            include "code/scripthandling/scriptfuncs_dispatch.asm"
CutsceneScriptTable:        include "code/script/fr/cutscenes/script_cutscenetable.asm"
RoomDialogueTable:          incbin  "assets_packed/roomdata/roomcharatertable.bin"
CharacterScriptTable:       include "code/script/fr/characters/script_charactertable.asm"
                            include "code/scripthandling/scriptfuncs_branch.asm"
ShopScriptFuncs:            include "code/script/fr/shops/script_shops.asm"
                            include "code/scripthandling/scriptfuncs_church.asm"
CharacterScriptFuncs:       include "code/script/fr/characters/script_characters.asm"
CutsceneScriptFuncs:        include "code/script/fr/cutscenes/script_cutscenes.asm"
Script:                     incbin  "assets_packed/script/script_fr.bin"
                            include "code/scripthandling/scriptfuncs_interpreter.asm"
SpriteIdToTalkSfx:          incbin  "assets_packed/script/spritetalksfx.bin"
                            include "code/scripthandling/scriptfuncs_specialchar.asm"
SpecialCharacterSfxList:    incbin  "assets_packed/script/charactertalksfx.bin"
                            include "code/scripthandling/scriptfuncs_items.asm"
ItemProperties:             incbin  "assets_packed/script/items.bin"
                            include "code/scripthandling/scriptfuncs_debugitems.asm"
                            include "code/scripthandling/articles/getitemarticle.asm"
ItemArticles:               incbin  "assets_packed/script/itemarticles/itemarticles_fr.bin"
                            include "code/scripthandling/articles/getitemusestring.asm"
ItemUseStringOffsets:       incbin  "assets_packed/script/itemarticles/itemuse_offsets.bin"
                            include "code/scripthandling/articles/getitemfoundstring.asm"
ItemFoundStringOffsets:     incbin  "assets_packed/script/itemarticles/itemfound_offsets.bin"
                            include "code/scripthandling/scriptfuncs_flags.asm"
                            include "code/scripthandling/scriptfuncs_names.asm"
SaveGameLocations:          incbin  "assets_packed/script/savegamelocations.bin"
                            include "code/scripthandling/islandmaplocations.asm"
IslandMapLocations:         incbin  "assets_packed/script/islandmaplocations.bin"
StringTables:               include "code/text/stringtables_fr.asm"
                            include "code/scripthandling/script_visualfx.asm"
SineTable:                  incbin  "assets_packed/misc/data/sinetable.bin"
                            include "code/misc/debugmenu.asm"
StringData:                 include "code/text/strings_fr.asm"
                            Align   $2
StringBankPtrs:             include "code/pointertables/strings/stringptrs_fr.asm"
                            PadTo   $038600
                            include "code/graphics/staticimages/staticgraphicjumps.asm"
SegaLogo:                   include "code/graphics/staticimages/segalogo_jp.asm"
                            include "code/graphics/staticimages/lithograph.asm"
LithographData:             include "code/graphics/staticimages/lithographdata.asm"
                            include "code/title/titlescreenentry.asm"
                            include "code/graphics/decomp_2d_map.asm"
TitleScreen:                include "code/title/titlescreen_fr.asm"
                            include "code/graphics/staticimages/climaxlogo.asm"
ClimaxLogoData:             include "code/graphics/staticimages/climaxlogodata.asm"
                            include "code/graphics/staticimages/islandmaproutines.asm"
IslandMap:                  include "code/graphics/staticimages/islandmap.asm"
                            PadTo   $044010
TilesetPtrTable:            include "code/pointertables/graphics/tilesetpointers.asm"
TilesetData:                include "code/graphics/tileset_data_frde.asm"
                            PadTo   $09B000
                            include "code/sprites/loadspritebehaviour.asm"
SpriteBehaviourOffsets:     incbin  "assets_packed/spritedata/behaviouroffsets.bin"
SpriteBehaviourTable:       incbin  "assets_packed/spritedata/behaviourtable_frde.bin"
                            Align   $2
                            include "code/maps/chestlookup.asm"
RoomChestOffsets:           incbin  "assets_packed/roomdata/chests/chestoffsets.bin"
ChestContents:              incbin  "assets_packed/roomdata/chests/chestcontents.bin"
                            Align   $2
                            include "code/maps/openchest.asm"
                            include "code/ending/endcredits.asm"
EndCreditText:              incbin  "assets_packed/strings/ending/credits_fr.bin"
                            Align   $2
                            include "code/ending/creditrenderer.asm"
EndCreditsData:             include "code/ending/endcreditsdata_fr.asm"
                            PadTo   $0A0A00
                            include "code/pointertables/maps/mappointers.asm"
                            include "code/system/regioncheckjump.asm"
RoomData_0:                 include "code/pointertables/maps/roomlist.asm"
RoomMaps:                   include "code/graphics/roommaps.asm"
                            Align   $2
RoomPals:                   include "code/palettes/roompals.asm"
RoomExits:                  incbin  "assets_packed/roomdata/warps/exits.bin"
RegionCheck:                include "code/system/regioncheck.asm"
                            PadTo   $120000
                            include "code/pointertables/sprites/spritegraphicsptr.asm"
SpriteGfxOffsetTable:       incbin  "assets_packed/spritedata/spritegfxoffsettable.bin"
SpriteAnimationPtrs:        include "code/pointertables/sprites/spriteanimations.asm"
SpriteFramePtrs:            include "code/pointertables/sprites/spriteanimationframes.asm"
SpriteFrames:               include "code/sprites/spriteframes.asm"
                            PadTo   $1A4400
                            include "code/sprites/spritefuncsjumptable2.asm"
                            include "code/sprites/spritepaletteload.asm"
SpritePalettes:             include "code/sprites/spritepalettes.asm"
                            include "code/gamelogic/ai/enemies1.asm"
                            include "code/gamelogic/ai/enemyaidispatch.asm"
                            include "code/gamelogic/ai/enemies2.asm"
                            include "code/gamelogic/ai/enemyaicommon.asm"
                            include "code/gamelogic/ai/enemies3.asm"
                            include "code/gamelogic/ai/projectilepal1.asm"
ProjectilePalette1:         incbin  "assets_packed/graphics/spritepalettes/projectile1.pal"
                            include "code/gamelogic/ai/projectilespawn.asm"
                            include "code/gamelogic/ai/enemies4.asm"
                            include "code/gamelogic/ai/projectilepal2.asm"
ProjectilePalette2:         incbin  "assets_packed/graphics/spritepalettes/projectile2.pal"
                            PadTo   $1AF800
BlocksetPrimaryPointers:    include "code/pointertables/blocks/primaryblocksetpointers.asm"
BlocksetSecondaryPointers:  include "code/pointertables/blocks/secondaryblocksetpointers.asm"
Blocksets:                  include "code/blocks/blocksets.asm"
                            PadTo   $1E0000
pcmbank0:                 incbin  "assets_packed/sound/pcmbank0.bin"
                            PadTo   $1E8000
pcmbank1:                 incbin  "assets_packed/sound/pcmbank1.bin"
                            PadTo   $1F0000
SoundBank3:                 incbin  "soundbank3.bin"
                            PadTo   $1F6000
SoundDriver:                incbin  "cube.bin"
                            PadTo   $1F8000
SoundBank4:                 incbin  "soundbank4.bin"
                            PadTo   $200000
