; enum CHR
CHR_Space:	 equ $00000000
CHR_BREAKING_SPACE: equ	$0000007B
CHR_BREAK_POINT: equ $0000007C
CHR_MULT:	 equ $00000080
CHR_FullStop:	 equ $000000D8
CHR_BEGIN_TALK:	 equ $000000D9
CHR_STR_BEGIN:	 equ $000000E9			  ; String begin
CHR_ARROW_PROMPT: equ $000000EA			  ; Down arrow prompt

; ---------------------------------------------------------------------------

; enum Constants
NUM_CHAR_NAMES:	 equ $0000003C
SCRIPT_STRINGS_BEGIN: equ $0000004D
