ResetSP:				dc.l *
ResetPC:				dc.l EntryPoint
BusError:				dc.l HandleGenericError
AddressError:			dc.l HandleAddressError
IllegalInstr:			dc.l HandleIllegalInst
DivBy0:					dc.l HandleDiv0
CHKInstr:				dc.l HandleGenericError
TRAPVInstr:				dc.l HandleGenericError
PrivViolation:			dc.l HandleGenericError
Trace:					dc.l HandleGenericError
LineA:					dc.l HandleGenericError
LineF:					dc.l HandleGenericError
Reserved0:				dc.l HandleGenericError
Reserved1:				dc.l HandleGenericError
Reserved2:				dc.l HandleGenericError
UninitInterrupt:		dc.l HandleGenericError
Reserved3:				dc.l HandleGenericError
Reserved4:				dc.l HandleGenericError
Reserved5:				dc.l HandleGenericError
Reserved6:				dc.l HandleGenericError
Reserved7:				dc.l HandleGenericError
Reserved8:				dc.l HandleGenericError
Reserved9:				dc.l HandleGenericError
Reserved10:				dc.l HandleGenericError
SpuriousInt:			dc.l HandleGenericError
IRQ1:					dc.l HandleUnexpectedInterrupt
EXT_Interrupt:			dc.l HandleUnexpectedInterrupt
IRQ3:					dc.l HandleUnexpectedInterrupt
HBlank_Interrupt:		dc.l HandleHBlankInterrupt
IRQ5:					dc.l HandleUnexpectedInterrupt
VBlank_Interrupt:		dc.l HandleVBlankInterrupt
IRQ7:					dc.l HandleIRQ7
Trap00:					dc.l Trap00Handler			; Play sound
Trap01:					dc.l Trap01Handler			; Run script command
Trap02:					dc.l Trap02Handler			; Run custom item shop script
Trap03:					dc.l HandleUnexpectedInterrupt
Trap04:					dc.l HandleUnexpectedInterrupt
Trap05:					dc.l HandleUnexpectedInterrupt
Trap06:					dc.l HandleUnexpectedInterrupt
Trap07:					dc.l HandleUnexpectedInterrupt
Trap08:					dc.l HandleUnexpectedInterrupt
Trap09:					dc.l HandleUnexpectedInterrupt
Trap0A:					dc.l HandleUnexpectedInterrupt
Trap0B:					dc.l HandleUnexpectedInterrupt
Trap0C:					dc.l HandleUnexpectedInterrupt
Trap0D:					dc.l HandleUnexpectedInterrupt
Trap0E:					dc.l HandleUnexpectedInterrupt
Trap0F:					dc.l HandleUnexpectedInterrupt
FP_BranchUnorderedCond:	dc.l HandleGenericError
FP_InexactResult:		dc.l HandleGenericError
FP_Div0:				dc.l HandleGenericError
FP_Underflow:			dc.l HandleGenericError
FP_OperandError:		dc.l HandleGenericError
FP_Overflow:			dc.l HandleGenericError
FP_SignalingNAN:		dc.l HandleGenericError
FP_UnimplementedType:	dc.l HandleGenericError
MMU_ConfigError:		dc.l HandleGenericError
MMU_IllegalOperation:	dc.l HandleGenericError
MMU_AccessViolation:	dc.l HandleGenericError
Reserved11:				dc.l HandleGenericError
Reserved12:				dc.l HandleGenericError
Reserved13:				dc.l HandleGenericError
Reserved14:				dc.l HandleGenericError
Reserved15:				dc.l HandleGenericError
