GameLoadScreenRoutines1:    include "code/title/saveselectmain.asm"
GameLoadScreenRoutines2:    include "code/title/savewindowrender.asm"
GameStartPalette:           incbin  "assets_packed/graphics/static/loadgame/loadgame.pal"
GameLoadScreenRoutines3:    include "code/title/saveselectmenu.asm"
InitialPlayerPal:           incbin  "assets_packed/graphics/static/loadgame/nigel.pal"
LoadGameScreenCharsCmp:     incbin  "assets_packed/graphics/static/loadgame/chars.lz77"
LoadGameScreenGfxCmp:       incbin  "assets_packed/graphics/static/loadgame/tiles.lz77"
LoadGameScreenTilemapCmp:   incbin  "assets_packed/graphics/static/loadgame/tilemap.rle"
                            Align   $2
GameLoadScreenRoutines4:    include "code/title/gamestartseq.asm"
